micronaut:
  application:
    name: micronaut-crud
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
flyway:
  datasources:
    default:
      enabled: true